### ISSUE TITLE
[Question]: Error handling

### ISSUE THREAD

**Issue by stunaz** [lelandrichardson/redux-pack#2]
Interesting library! Very Nice!
I have been using `redux-thunk` so far along with the `fetch` library. works well.
`redux-pack` will be a big addidtion for me.

But really my main concern is `errors handling`. Maybe it is not the right place to ask it, but how would you globally handle `fetch` errors. The `catch` section of the `fetch promise` get called mainly where there is a network outage. How would **generally** handle `500`, `403`, `401` or event `400` errors?

**Comment by lelandrichardson** [comment]
@stunaz thanks for asking.  Right now the `failure` case will get called whenever the promise rejects... but as you mention, this doesn't happen by default with 400/500 level error codes with `fetch`.

If you'd like `fetch` to reject in these cases, one thing you can do is something like the following:

```
class APIError extends Error {
  constructor(response) {
    this.status = response.status;
    // ... more here potentially
  }
}

const myfetch = (...args) => fetch(...args)
  .then(r => {
    if (!r.ok) {
      throw new APIError(r);
    }
    return r;
  });
```

And then you can use `myfetch` instead of `fetch` and it will automatically fall into the `failure` case. You can also apply specific logic for your own API responses etc.


Does that answer your question?

**Comment by stunaz** [comment]
yeah, makes sense
