### ISSUE TITLE
Actions Are Called Twice

### ISSUE THREAD

**Issue by fredguest** [lelandrichardson/redux-pack#34]
Very cool library, I like the approach. Thanks for building and OSing it!

I've swapped in redux-pack for redux-thunk and rewritten an action called `getBroadcasts` from this redux-thunk action:

```js
export function getBroadcasts() {
  return async (dispatch) => {
    dispatch({ type: 'GET_BROADCASTS_INITIATED' });

    try {
      const { data: { results } } = await api.get('/broadcasts');
      dispatch({ type: 'GET_BROADCASTS_SUCCEEDED', payload: results });
    } catch (error) {
      dispatch({ type: 'GET_BROADCASTS_FAILED', payload: error });
    }
  };
}
```

to this redux-pack action:

```js
export function getBroadcasts() {
  return {
    type: 'GET_BROADCASTS',
    promise: api.get('/broadcasts')
  }
}
```

What I observe in the console when the relevant page loads is that while the redux-thunk action was called only once:

<img width="496" alt="thunk" src="https://cloud.githubusercontent.com/assets/1145624/21736320/b2a99b36-d424-11e6-9699-663326708783.png">

the redux-pack action is called twice, and returns once with an undefined payload, and once with a successful payload:

<img width="540" alt="pack" src="https://cloud.githubusercontent.com/assets/1145624/21736329/bf399216-d424-11e6-96a0-6877a33ffd0e.png">

I assume this is expected behavior, I just wanted to confirm.

**Comment by rockchalkwushock** [comment]
@fredguest I'm not on the dev team for `redux-pack` but I have seen the same behavior. Since what would normally be our _payload_ is now a _promise_ I believe (don't take my word for it) this is happening because the promise has not returned yet so your _payload/promise_ is `undefined`. It's kind of like the actionType is dispatched initially and then when the _promise_ is resolved or rejected the reducer fires updating the state. 

_initial dispatch of action_
![screen shot 2017-01-07 at 10 47 47 am](https://cloud.githubusercontent.com/assets/19720404/21743406/33f504e4-d4c7-11e6-8699-c95b1392ca19.png)

_promise resolved_
![screen shot 2017-01-07 at 10 48 25 am](https://cloud.githubusercontent.com/assets/19720404/21743408/408b9f24-d4c7-11e6-8079-6af1bfbdc31a.png)

**Comment by evandavis** [comment]
It looks like there are intentionally 2 dispatches, [on start](https://github.com/lelandrichardson/redux-pack/blob/master/src/middleware.js#L28) and then on one of [success](https://github.com/lelandrichardson/redux-pack/blob/master/src/middleware.js#L40) or [failure](https://github.com/lelandrichardson/redux-pack/blob/master/src/middleware.js#L54).

The nice part of having the 3-phase action (old way) is that you can have _other_ reducers react to those actions. I think you lose that here, but maybe I'm missing something?

**Comment by lelandrichardson** [comment]
@evandavis curious why you think you lose that ability?  It is certainly possible for multiple reducers to react to actions still.

**Comment by evandavis** [comment]
I hadn't thought it through when I posted; I'd just call `handle`  and define only the relevant transitions. 😅

**Comment by fredguest** [comment]
Closing as this has been confirmed as expected behavior. Thanks for the discussion!
