### ISSUE TITLE
dispatch action in side effect hooks

### ISSUE THREAD

**Issue by djkirby** [lelandrichardson/redux-pack#54]
> ### Adding side-effects with event hooks
> 
> ...
> 
> redux-pack lets you do that through event hooks functions. These are functions attached to the meta attribute of the original action. They are called with two parameters:
> 
> 1. the matching step payload (varies based on the step, details below)
> 2. the getState function

It would be nice to be able to dispatch an action inside the side effect handlers. Is there a good reason for not passing `dispatch` along with `getState` here? Thanks.

**Comment by icopp** [comment]
It seems like it'd be a perfect place to set up dispatches. You'd basically get all the functionality of `redux-loop`, but while still keeping the reducers "dumb" and keeping all multi-step logic in the action creators.

**Comment by djkirby** [comment]
Any thoughts on this @lelandrichardson? I would open a PR if desired. Or I'd be interested in how you would handle a case where you want to dispatch an action as a result of another action -- it seems this doesn't fully replace what thunk would give you.

**Comment by cruzj6** [comment]
Wouldn't this seemingly break the point of the library. One of the major advantages is to avoid dispatching multiple actions from one actionCreator. This is because that breaks the cycle of ```component->action->reducer```, changing it to ```component->action->( 0-infinity more actions with difficult to track side effects )->( reduce for each action in order of actions )```.

Doing this would cause the same issue of side effects that sagas/thunk create, and also makes it easier to introduce race conditions between reducing each action if multiple of them are async.

**Comment by djkirby** [comment]
I ended up just using middleware for these cases.
